### ISSUE TITLE
`res` broken

### ISSUE THREAD

**Issue by jacobwgillespie** [holman/dotfiles#133]
I cannot seem to get `res` to work for me - the error I'm getting is the following:

```
/Users/jacobwg/.dotfiles/bin/res:1491:1495: execution error: System Events got an error: Can’t get radio group 1 of group 1 of tab group 1 of window "Built-in Retina Display" of application process "System Preferences". Invalid index. (-1719)
```

Not sure what's going on... :/

**Comment by cameronmalek** [comment]
For future reference, I got this working for my 13" retina MBP on Yosemite 10.10.3 by making the two following changes (in `diff` format):

    -set index1 to 3 -- 1440 x 900 (Best for Retina)
    -set index2 to 5 -- 1920 x 1200 (More Space)
    +set index1 to 2 -- 1280 x 800 (Best for Retina)
    +set index2 to 4 -- 1680 x 1050 (More Space)

and also, less obviously:

    -      tell radio group 1 of group 1
    +      tell radio group 1 of group 2

I was fiddling with this for an hour and got to the point where I was desperately entering in different group numbers until `radio group 1 of group 2` worked!
