### ISSUE TITLE
Git function does not exist

### ISSUE THREAD

**Issue by mecampbellsoup** [holman/dotfiles#135]
Seems like there may be an error with one of the aliases in `git/aliases.zsh`:

``` bash
alias gcb='git copy-branch-name'
```

After running a quick `ag` within the `.dotfiles` directory, that git function doesn't appear to be defined anywhere (and it's not a stock git function either). 

Am I missing something?

**Comment by partounian** [comment]
I know this is 2 years ago, but how did you fix this? I setup a new server but can't get my aliases to work.

**Comment by mecampbellsoup** [comment]
@partounian are you sourcing the aliases file? IIRC there's an `aliases.zsh` file you must source. I'm using OMZ at this point so can't say too much more.

**Comment by partounian** [comment]
I'm using OMZ, with this config on the zshrc everything is sourced supposedly. For me the problem is weird. Some aliases work, and some don't.
