### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by dfischer** [holman/dotfiles#188]
This time around of using it - it seems I'm not having any luck in it working. If I restart terminal it's still using bash.

By default it's not getting set to ZSH. 

If I try to run zsh manually:

```
$zsh
/usr/local/Cellar/rbenv/0.4.0/libexec/../completions/rbenv.bash:16: command not found: complete
```

**Comment by larslevie** [comment]
Check out this issue https://github.com/sstephenson/rbenv/issues/487. I had the same problem and @elado's solution worked for me.
