### ISSUE TITLE
c function doesn't work entirely

### ISSUE THREAD

**Issue by pruett** [holman/dotfiles#190]
this is likely a lack of understanding `zsh` functions, but the `c` function doesn't seem to work for me

the `_c` function works as expected, with `c <tab>` correctly completing all the folders within the my specified directory. but when i complete the call, `c some-directory <enter>` the call doesn't complete...the terminal window hangs with `pbcopy <spinner>` in the tab.

anyone know what could cause this? where i could look?

**Comment by pruett** [comment]
im an idiot

**Comment by mecampbellsoup** [comment]
@pruett for me `c <tab>` no longer autocompletes, that is shows the available files in my `$PROJECTS` directory. what was your issue here?

**Comment by avr** [comment]
@mecampbellsoup try editing the `functions/_c` file and remove line 1 - 2.  I read somewhere that the `#compdef c` needs to be on the first line.

Once you've done this:
- delete your `~/.zcompdump` file
- reload your terminal (which will regenerate `~/.zcompdump`

You can look through that `.zcompdump` file to make sure there is a line that defines `'c'  '_c'`.  This change was made a few months ago, but I didn't notice it until recently - I'm assuming that cache file was rewritten and I lost the completion function.

**Comment by pruett** [comment]
@mecampbellsoup my issue was that I had a conflicting alias mapped to the same `c` character

thanks for the clarification @avr

**Comment by mecampbellsoup** [comment]
@avr thanks man! Working great again, cheers ::beer::
