### ISSUE TITLE
How to uninstall it

### ISSUE THREAD

**Issue by vokus** [holman/dotfiles#194]
I really want to get rid of it...

**Comment by holman** [comment]
We don't have an uninstall process quite yet, but if you delete the dotfiles itself (`~/.dotfiles`) and then delete the symlinks you have installed in your home directory, you should be fine. So things like `.zshrc`, `.gitconfig`, `.vimrc`, etc can be removed. Any files we almost overwrote we would move to `.backup`, so if you see things like `.vimrc.backup` you can rename that back to `.vimrc`.

Might be a little confusing dealing with all this, so if you have any questions let me know and I'd love to help you out!

**Comment by vokus** [comment]
Thank you very much for response. Sory for stupid question, but can you tell me with file is responsible for prompt colors? I have almost reversed it, this is the onlu thing that is left :)

**Comment by holman** [comment]
That should be in https://github.com/holman/dotfiles/blob/master/zsh/prompt.zsh, which should get deleted once you delete the directory. You may need to restart your terminal if you haven't already.
