### ISSUE TITLE
Need help getting rust/cargo zsh completion to work.

### ISSUE THREAD

**Issue by thepreacher** [holman/dotfiles#198]
First of thanks for your labour of love. Yours is the only dotfiles that I can understand a little. Ok so I have installed rust with brew and as part of that it installs cargo (the build tool + for rust). On the post install comment, it said zsh completion was installed at /usr/local/share/zsh/site-functions. I therefore - trying to follow the modular approach - created a rust folder in .dotfiles/. In the rust folder I created a completion.zsh file with the following content:

```sh
# Uses rust's cargo autocompletion
completion='$(brew --prefix)/share/zsh/site-functions/_cargo'

if test -f $completion
then
  source $completion
fi
```
My understanding is this is all I need to do. Upon starting a new shell, I am able to complete the > cargo command but not the options like build, run, package etc. Pressing the tab key only lists the folders in the current directory.
The behavior I was expecting is like how it works for brew. At the prompt when I type brew and hit tab, I get a list of all the options and what each does.

I'm rumbling but I hope I've expressed myself. Below is the content of my .localrc file incase it provides some assistance.

```sh
# Use homebrew tools over Mac counter parts
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

#begin .localrc
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
#export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

# use gpip command below to install into global pip environment
gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

# Path for golang
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Additional zsh completions
fpath=(/usr/local/share/zsh-completions $fpath) 
#end .localrc
```

Thanks.

**Comment by holman** [comment]
I'm not too sure, actually- haven't used Rust yet, and I don't set up the completions stuff too often to really have a good understanding of how to troubleshoot it. The way you set up completions appears to be what you'd want.

Maybe try `which cargo` just to make sure it's using the correct `cargo` and not some other thing?

Would be curious if anyone else watching this repo might be able to help out with this, too.

**Comment by thepreacher** [comment]
```which gargo``` gives me ```/usr/local/bin/cargo``` which is the right cargo to use. I'll leave this open for a while and if there is still no solution I'll close it or you close it. Thanks anyway your dofiles has opened my eyes to so much.
