### ISSUE TITLE
Some documentation will really really be great

### ISSUE THREAD

**Issue by najela** [holman/dotfiles#202]
I'm a newbie and I just cloned your dotfiles. Now I have a big problem configuring it. I would like to change the `ZSH theme` together with the `$PS1` environment variable. It hasn't been easy to do this so far. 

I tried editing `.dotfiles/zsh/zshrc.symlink` and added the line 

```
ZSH_THEME="robbyrussell"
```

But the theme wasn't changed

Please can you help with some documentation?

**[Edit]**
https://github.com/holman/dotfiles/issues/33#issuecomment-87501560 solved my problem
But the documentation would be cool imo

**Comment by holman** [comment]
Yeah, I should really go in and detail the customizations available at some point.

For the prompt, you'll want to edit https://github.com/holman/dotfiles/blob/master/zsh/prompt.zsh — that'll let you customize it as you see fit.

Theme-wise it's incompatible with oh-my-zsh though.

**Comment by najela** [comment]
Thanks man :+1:
