### ISSUE TITLE
Path to Ruby Gems is not being loaded on zsh

### ISSUE THREAD

**Issue by najela** [holman/dotfiles#212]
eg

```bash
[najela@Achos-MacBook-Pro:git-repo on  master ]$ travis monitor
zsh: correct 'travis' to '_travis' [nyae]? n
zsh: command not found: travis
```

**Comment by holman** [comment]
Did you change something recently? (i.e. does `travis` still exist on your system?)

**Comment by najela** [comment]
Yep  i upgraded to el capitain. `travis`  is still in my system intact all my gems (sass, compass, etc)  give me this error.

**Comment by hectorcascos** [comment]
This should work https://github.com/thoughtbot/dotfiles/commit/15de0bcfee0d7a6472da048029408c5faedbae4e
Note that the correct command is:
```
sudo mv /etc/{zprofile,zshenv}
```

**Comment by najela** [comment]
doing

`sudo mv /etc/zprofile /etc/zshenv` didn't work on my end. Its worth noting that I'm using `oh-my-zh`

**Comment by najela** [comment]
Well I tried reinstalling all my ruby gems and they now load correctly
