### ISSUE TITLE
Powerline shell

### ISSUE THREAD

**Issue by joshhornby** [holman/dotfiles#214]
Hey,

Can you give me some tips in order to get this powerline-shell package working?

https://github.com/milkbikis/powerline-shell

Thanks :+1:

**Comment by holman** [comment]
Not sure about that in particular, but everything you'll want to modify here would be in [`prompt.zsh`](https://github.com/holman/dotfiles/blob/master/zsh/prompt.zsh).

**Comment by joshhornby** [comment]
Thanks :)

**Comment by sergii-frost** [comment]
@joshhornby I see that issue is closed, but could you please provide an example how you got it working wth power line shell?

**Comment by joshhornby** [comment]
@sergii-frost Take a look at my repo here https://github.com/joshhornby/dotfiles

https://github.com/joshhornby/dotfiles/blob/3d351b6aa50b1f7bfc0677169141e030b34dade7/zsh/prompt.zsh is a good place to start I'd suggest.

**Comment by sergii-frost** [comment]
@joshhornby great, thank you!
