### ISSUE TITLE
Nothing works unless I run zsh once

### ISSUE THREAD

**Issue by MickeyKay** [holman/dotfiles#216]
I've got these dotfiles forked and over at https://github.com/MickeyKay/.dotfiles/, and have them up and running just fine on my old machine. On my new machine however, things are not quite working. I can get all my aliases, functions, completions, etc to work, but only if I run `zsh` one time. For example, if I try to run one of my aliases, `gs` (git status) immediately after I open iTerm, I get `gs: command not found`. If I run `zsh` and then `gs` again, the alias suddenly works. Every time I restart iTerm I have to do this to get things to work. Any idea why that might be?

Here's a screencast to help clarify: http://recordit.co/Od31rK8jVd

**Comment by holman** [comment]
Yeah- that's because it requires zsh. I'm not sure how things are done in iTerm, but in Terminal I just set it to run all new tabs with `zsh`:

<img width="632" alt="screen shot 2015-11-05 at 2 24 36 pm" src="https://cloud.githubusercontent.com/assets/2723/10983694/f90b2098-83c8-11e5-85a9-7b673b79f4b6.png">

**Comment by MickeyKay** [comment]
Ahhhhh - thank you!!!!

**Comment by jacobwgillespie** [comment]
When I set up my environment, I install zsh via brew with do `brew install zsh` for the latest and greatest, then change my default shell with:

```shell
$ sudo echo "/usr/local/bin/zsh" >> /etc/shells
$ chsh -s /usr/local/bin/zsh
```

Adding the `/usr/local/bin/zsh` line to `/etc/shells` allows it to be used as a user shell, and then the `chsh` changes your user's default shell.

Just another idea for defaulting to zsh.
