### ISSUE TITLE
Automatic installation of Homebrew fails due to missing RETURN

### ISSUE THREAD

**Issue by andygrunwald** [holman/dotfiles#238]
I used your dotfiles as a base for mine. Thank you for this great work.
I wiped my MacBook and observed that the first install stucks at the place of Homebrew install.

The reason is that the Install script requires a user interaction (Press Return).
Check this: https://github.com/Homebrew/install/blob/master/install#L57 and https://github.com/Homebrew/install/blob/master/install#L186

Seems that there is a HEADLESS install, but requires some command line tools?

**Comment by andygrunwald** [comment]
https://github.com/Homebrew/install/issues/44

**Comment by holman** [comment]
Think this is fixed by #284.
