### ISSUE TITLE
script/install doesn't run the installers

### ISSUE THREAD

**Issue by glevine** [holman/dotfiles#242]
I was noticing that a new installer I added wasn't executing. So I put `echo "> find installers"` after `brew bundle` in `script/install`. I ran `dot`. I never saw the line I added. `brew bundle` was the last thing to execute.

**Comment by glevine** [comment]
Forgot to add one more thing. I commented out `brew bundle` and then the installers ran successfully. So something about `brew bundle` seems to be preventing the installers from running when running `dot`.

**Comment by michaelbaisch** [comment]
Same here after a clean install with Sierra.

**Comment by conrman** [comment]
I tried running `script/bootstrap` on a fresh install of Sierra and it seems to hang on 'installing dependencies...'

I ended up having to directly run `source bin/dot` in order to get the dot script to install homebrew and everything properly

**Comment by glevine** [comment]
@conrman - I believe that is a different issue. What you probably experienced was that homebrew was expecting you to hit Enter before continuing. See https://github.com/holman/dotfiles/blob/master/script/bootstrap#L146-L147. `installing dependencies` is printed to stdout and then all output from running `bin/dot` is redirected to `/tmp/dotfiles-dot`. Homebrew is installed as a part of `bin/dot` -- if it doesn't exist -- and the installer requires you to hit Enter after it tells you what it is going to do. Unfortunately, you don't see this because it is actually written to `/tmp/dotfiles-dot`. This only happens when you run `script/bootstrap`. When you run `bin/dot` directly, all output is written to stdout.

**Comment by Macxim** [comment]
Same here.
Has anyone found a workaround for this?

**Comment by vforge** [comment]
@Macxim Yup, run `bin/dot` manually after `script/bootstrap`

**Comment by holman** [comment]
Think this is fixed by #284.
