### ISSUE TITLE
Better history searching with arrow keys

### ISSUE THREAD

**Issue by gatspy** [holman/dotfiles#248]
[Better history searching with arrow keys](https://coderwall.com/p/jpj_6q/zsh-better-history-searching-with-arrow-keys) 
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

**Comment by nerdgore** [comment]
FWIW I managed to get better searching with just autoloading `history-search-end`

```
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end
```
For me this has exactly the same result.
