### ISSUE TITLE
Obsolete, broken code in zsh/config.zsh

### ISSUE THREAD

**Issue by carhartl** [holman/dotfiles#253]
I believe the following code in zsh/config.zsh is obsolete and should be removed:

```
if [[ -n $SSH_CONNECTION ]]; then
  export PS1='%m:%3~$(git_info_for_prompt)%# '
else
  export PS1='%3~$(git_info_for_prompt)%# '
fi
```

`PS1` is not used as soon as `PROMPT` is set (which is done elsewhere in these dotfiles), furthermore the function `git_info_for_prompt` seems to no longer exist.

**Comment by holman** [comment]
Cheers!
