### ISSUE TITLE
Is there a way to ad antigen?

### ISSUE THREAD

**Issue by SolidRhino** [holman/dotfiles#254]
Is there a way to add antigen? I've tried it on my fork, but the configuration then flips.

**Comment by holman** [comment]
No idea; I haven't played with any of that stuff.

**Comment by StewartJarod** [comment]
@SolidRhino seems like you would just need to clone antigen somewhere and then source the antigen.zsh from somewhere in the dotfiles.

Prolly ideal to set up an `antigen` folder with an `install.sh` that will clone it if it doesn't exist and a `config.zsh` that sources the `antigen.zsh` file

**Comment by OmeGak** [comment]
You can probably take a look at how I solved this.
https://github.com/OmeGak/dotfiles/tree/master/zsh

Essentially, I have antigen setup as a git submodule in my dotfiles. To make use it, I load [`antigenrc`](https://github.com/OmeGak/dotfiles/blob/master/zsh/antigen/antigenrc) it on my [`.zshrc`]( https://github.com/OmeGak/dotfiles/blob/master/zsh/zshrc.symlink#L21).

**Comment by pranavbhargava** [comment]
I have a fork and added it the way @stewartjarod suggested. 
https://github.com/pranavbhargava/.dotfiles
