### ISSUE TITLE
zle widget newtab not defined (?)

### ISSUE THREAD

**Issue by carhartl** [holman/dotfiles#256]
In zsh/config.zsh I noticed the zle widget `newtab` being defined:

https://github.com/holman/dotfiles/blob/c3c6d314ce0205efebd3c468bf7100f566d71c41/zsh/config.zsh#L34

Though I'm not sure how it works. There doesn't seem to be a built-in widget of that name, nor can I find it being defined anywhere. Invoking it gives me an error:

```
No such shell function `newtab'
```

Is it broken (maybe incompletely taken from another dotfiles repo) or what am I missing?

**Comment by holman** [comment]
Yeah, no idea what that is. I went and removed it, thanks. 🎉
