### ISSUE TITLE
bin programs not working

### ISSUE THREAD

**Issue by jhanstra** [holman/dotfiles#279]
Really confused why the executables in my `bin/` do not work. I'm sure I'm missing something dumb, but I can't understand why I don't have access to them. I have customized the location of `$ZSH`, but that shouldn't matter, correct?

My path:
`/Users/jhanstra/JH/projects/dotfiles/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
![image](https://cloud.githubusercontent.com/assets/1919535/22672708/99d93cdc-eca3-11e6-9920-88dcf97a6724.png)

/dotfiles/bin folder, e shown:
![image](https://cloud.githubusercontent.com/assets/1919535/22672653/3f8b10ac-eca3-11e6-85a2-c44231a81b65.png)

e not found:
![image](https://cloud.githubusercontent.com/assets/1919535/22672680/5d7925c2-eca3-11e6-82f6-4a3279aef807.png)

**Comment by holman** [comment]
Hm. If it's in `$PATH` I think it *shouldddddddddddd* work. Stupid, but: you've reloaded/restarted your shell, yeah?

**Comment by jhanstra** [comment]
Yep, I have. I'm using Hyper but I also tried with Terminal and got the same thing.

I'm 97% sure it will end up being something stupid though haha. Have other people customized where $ZSH lives?

**Comment by holman** [comment]
I'm sure others have. Happy if someone else jumps in with their two cents, though!

**Comment by jacobwgillespie** [comment]
Two things to check:

1. what's the output of `which e` without using `sudo`?
1. what's the output of `ls -l /Users/jhanstra/JH/projects/dotfiles/bin/e` (to grab the file permissions)?

**Comment by jhanstra** [comment]
Thanks for your help @jacobwgillespie. Here's what I have:

![image](https://cloud.githubusercontent.com/assets/1919535/22676538/0354fc44-ecba-11e6-849b-509ad69a1979.png)

Not too familiar with permissions - should those files have higher permissions granted?

**Comment by jhanstra** [comment]
Got it. Changed permissions of the files in bin/ with `find bin -type f -exec chmod 700 {} \;`

**Comment by holman** [comment]
✨
