### ISSUE TITLE
Some aliases work and some don't?

### ISSUE THREAD

**Issue by partounian** [holman/dotfiles#288]
Sorry for putting this here if this is out of scope, but my dotfiles is heavily based on yours, and for some reason on a new install only some aliases work. For example in the same file "gs" (git status) doesn't work, but "gd" (git diff) does. Has anyone reported similar issues?

https://github.com/partounian/dotfiles

**Comment by jacobwgillespie** [comment]
What's the output of `which gs` and `which gd`?

**Comment by partounian** [comment]
```
➜  ~ which gs
gs not found
➜  ~ which gd
gd: aliased to git diff
```
