### ISSUE TITLE
c function not working

### ISSUE THREAD

**Issue by rojobuffalo** [holman/dotfiles#296]
The `c` function gives me autocomplete for projects in my Code folder, but when I hit `<enter>`, I get this error: 

```
Error: cannot read infile: [Errno 2] No such file or directory: 'example_app'
```

`which c` returns
```
c: aliased to pygmentize -O style=monokai -f console256 -g
```

` cd "$PROJECTS/example_app"` does work, so that variable is correct for the path.

**Comment by jacobwgillespie** [comment]
The issue is that in your `system/aliases.zsh`, you have overridden the `c` function with an alias:

https://github.com/rojobuffalo/dotfiles/blob/3161d37ebcb7f6e766aca0207dc103f670adff71/system/aliases.zsh#L20-L22

You'll want to remove or rename that alias so that `c example_app` works again.

**Comment by rojobuffalo** [comment]
@jacobwgillespie Thanks for pointing that out. I feel dumb for missing that.

**Comment by jacobwgillespie** [comment]
No worries!  Seems like it's usually something small 👍
