### ISSUE TITLE
What happened to the Brewfile?

### ISSUE THREAD

**Issue by Kylar13** [holman/dotfiles#350]
I've noticed there's no longer a Brewfile, and was wondering what the reason for that is, since I think it was very handy and I'm unsure as to why you would not want that

**Comment by holman** [comment]
Hi! Yeah- just ended up not using it personally. It was a usually out-of-date list of apps, which at some point felt worse than having no list at all. :)

I still like the idea of it, though, so it's something that I might bring back in the future, maybe!

**Comment by rojobuffalo** [comment]
are you doing anything to track which formulas and casks you have installed in homebrew? if you were bootstrapping a new computer, how would you add your brew dependencies?

**Comment by holman** [comment]
Nope- I'm not personally doing anything right now. I think the Brewfile approach makes a lot of sense for a new setup, though!
