### ISSUE TITLE
Integration with oh-my-zsh

### ISSUE THREAD

**Issue by jrhorn424** [holman/dotfiles#70]
Anyone have any clever ideas for including oh-my-zsh in dotfiles? I gave up after a few hours last night once I realized dotfiles was loading _every single plugin_ in the oh-my-zsh tree, since they all end in `.zsh`. Maybe I should just define a different extension for sourcing?

**Comment by joech4n** [comment]
Both the @holman dotfiles and oh-my-zsh seem to use the $ZSH env variable.

Maybe setting the var before any oh-my-zsh commands?

    ZSH=~/.oh-my-zsh upgrade_oh_my_zsh

**Comment by wackywendell** [comment]
I think it makes sense for both projects to not name it `$ZSH`, but something more specific: `$ZSHDOT` here, and maybe `$OMZSH` there. What do others think? Should I submit a PR?

**Comment by j-walker23** [comment]
That makes sense to me. I was surprised to see the variable named like that for two separate systems. Wondered if it was some convention i didn't understand.
